name             : "MUTH Boravy"
# logo: /assets/img/...png
descritpion      : PhD in Nuclear Engineering
show_download    : true
theme            : jekyll-theme-minimal

url              : https://muthboravy007.github.io/ravy1991.github.io
baseurl          : ""
repository       : "https://muthboravy007/ravy1991.github.io"
