name             : "MUTH Boravy"
# logo: /assets/img/...png
descritpion      : PhD in Nuclear Engineering
show_download    : true
theme            : jekyll-theme-minimal

#url              : https://muthboravy007.github.io/ravy1991.github.io
#baseurl          : ""
#repository       : "https://muthboravy007/ravy1991.github.io"

author: 
  # Biographic information
  avatar           : "profile.png"
  name             : "MUTH Boravy"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Earth"
  employer         : "Institute Of Technology of Cambodia (ITC)"
  uri              : # URL
  email            : "muth.boravy@itc.edu.kh" 

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.se/citations?user=Bz3EEdwAAAAJ&hl=en&oi=ao"
  researchgate     : "https://www.researchgate.net/profile/Boravy-Muth-2?ev=hdr_xprf"

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "muthboravy007"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")  

  # Publication Category - The following the list of publication categories and their headings
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

  
